[workspace]
resolver = "3"
members = ["platform/rust/mongo", "services/inventory", "services/payment"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = "0.12"
prost = "0.13"
uuid = { version = "1", features = ["v4"] }
tonic-build = "0.12"
prost-types = "0.13"
mockall = "0.14"
mongodb = "3"
platform-mongo = { path = "platform/rust/mongo" }
serde = { version = "1", features = ["derive"] }
url = "2"
