// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package services

import (
	"context"

	"github.com/BeInBloom/big-deal/services/order/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) Get(ctx context.Context, id models.OrderId) (models.OrderSnapshot, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.OrderSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderId) (models.OrderSnapshot, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderId) models.OrderSnapshot); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.OrderSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.OrderId) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id models.OrderId
func (_e *MockOrderRepo_Expecter) Get(ctx interface{}, id interface{}) *MockOrderRepo_Get_Call {
	return &MockOrderRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockOrderRepo_Get_Call) Run(run func(ctx context.Context, id models.OrderId)) *MockOrderRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrderId
		if args[1] != nil {
			arg1 = args[1].(models.OrderId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_Get_Call) Return(orderSnapshot models.OrderSnapshot, err error) *MockOrderRepo_Get_Call {
	_c.Call.Return(orderSnapshot, err)
	return _c
}

func (_c *MockOrderRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id models.OrderId) (models.OrderSnapshot, error)) *MockOrderRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) Save(ctx context.Context, order models.OrderSnapshot) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.OrderSnapshot) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.OrderSnapshot
func (_e *MockOrderRepo_Expecter) Save(ctx interface{}, order interface{}) *MockOrderRepo_Save_Call {
	return &MockOrderRepo_Save_Call{Call: _e.mock.On("Save", ctx, order)}
}

func (_c *MockOrderRepo_Save_Call) Run(run func(ctx context.Context, order models.OrderSnapshot)) *MockOrderRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.OrderSnapshot
		if args[1] != nil {
			arg1 = args[1].(models.OrderSnapshot)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_Save_Call) Return(err error) *MockOrderRepo_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepo_Save_Call) RunAndReturn(run func(ctx context.Context, order models.OrderSnapshot) error) *MockOrderRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPartService creates a new instance of MockPartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPartService {
	mock := &MockPartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPartService is an autogenerated mock type for the PartService type
type MockPartService struct {
	mock.Mock
}

type MockPartService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPartService) EXPECT() *MockPartService_Expecter {
	return &MockPartService_Expecter{mock: &_m.Mock}
}

// ListParts provides a mock function for the type MockPartService
func (_mock *MockPartService) ListParts(ctx context.Context, ids []models.PartId) (models.Parts, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 models.Parts
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.PartId) (models.Parts, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.PartId) models.Parts); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.Parts)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.PartId) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPartService_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockPartService_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []models.PartId
func (_e *MockPartService_Expecter) ListParts(ctx interface{}, ids interface{}) *MockPartService_ListParts_Call {
	return &MockPartService_ListParts_Call{Call: _e.mock.On("ListParts", ctx, ids)}
}

func (_c *MockPartService_ListParts_Call) Run(run func(ctx context.Context, ids []models.PartId)) *MockPartService_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.PartId
		if args[1] != nil {
			arg1 = args[1].([]models.PartId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPartService_ListParts_Call) Return(parts models.Parts, err error) *MockPartService_ListParts_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *MockPartService_ListParts_Call) RunAndReturn(run func(ctx context.Context, ids []models.PartId) (models.Parts, error)) *MockPartService_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentService creates a new instance of MockPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentService {
	mock := &MockPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentService is an autogenerated mock type for the PaymentService type
type MockPaymentService struct {
	mock.Mock
}

type MockPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentService) EXPECT() *MockPaymentService_Expecter {
	return &MockPaymentService_Expecter{mock: &_m.Mock}
}

// PayOrder provides a mock function for the type MockPaymentService
func (_mock *MockPaymentService) PayOrder(ctx context.Context, userId models.UserId, orderId models.OrderId, method models.PaymentMethod) (models.TransactionId, error) {
	ret := _mock.Called(ctx, userId, orderId, method)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 models.TransactionId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserId, models.OrderId, models.PaymentMethod) (models.TransactionId, error)); ok {
		return returnFunc(ctx, userId, orderId, method)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.UserId, models.OrderId, models.PaymentMethod) models.TransactionId); ok {
		r0 = returnFunc(ctx, userId, orderId, method)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.TransactionId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.UserId, models.OrderId, models.PaymentMethod) error); ok {
		r1 = returnFunc(ctx, userId, orderId, method)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type MockPaymentService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - userId models.UserId
//   - orderId models.OrderId
//   - method models.PaymentMethod
func (_e *MockPaymentService_Expecter) PayOrder(ctx interface{}, userId interface{}, orderId interface{}, method interface{}) *MockPaymentService_PayOrder_Call {
	return &MockPaymentService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, userId, orderId, method)}
}

func (_c *MockPaymentService_PayOrder_Call) Run(run func(ctx context.Context, userId models.UserId, orderId models.OrderId, method models.PaymentMethod)) *MockPaymentService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.UserId
		if args[1] != nil {
			arg1 = args[1].(models.UserId)
		}
		var arg2 models.OrderId
		if args[2] != nil {
			arg2 = args[2].(models.OrderId)
		}
		var arg3 models.PaymentMethod
		if args[3] != nil {
			arg3 = args[3].(models.PaymentMethod)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) Return(transactionId models.TransactionId, err error) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(transactionId, err)
	return _c
}

func (_c *MockPaymentService_PayOrder_Call) RunAndReturn(run func(ctx context.Context, userId models.UserId, orderId models.OrderId, method models.PaymentMethod) (models.TransactionId, error)) *MockPaymentService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}
